// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isdzbrcaavuhzheahfss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZHpicmNhYXZ1aHpoZWFoZnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODc2OTQsImV4cCI6MjA2MjE2MzY5NH0.1VSAgQUteqFyWgr1Z0W-YtBroFZDyZGUryhTzqcEAXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);